@baseurl = http://127.0.0.1:3000

### TESTANDO O HELLO WORLD

GET {{baseurl}}/

### AUTORES

### LISTANDO TODOS OS AUTORES

GET {{baseurl}}/autores/todos/





### LIVROS

GET {{baseurl}}/livros/todos/