@baseurl = http://127.0.0.1:3000

### TESTANDO O HELLO WORLD

GET {{baseurl}}/

### AUTORES

### LISTANDO TODOS OS AUTORES

GET {{baseurl}}/autores/todos/

### LISTANDO UM AUTOR ESPECIFICO

GET {{baseurl}}/autores/3/

### CRIANDO UM AUTOR NO BANCO DE DADOS

POST {{baseurl}}/autores/
Content-Type: application/json

{
    "nome": "Gabriel Lourenco",
    "cpf": "12312323329",
    "nacionalidade": "Portugues",
    "idade": 90
}

### ATUALIZANDO UM AUTOR NO BANCO DE DADOS

PATCH {{baseurl}}/autores/35
Content-Type: application/json

{
    "nome": "Gabriel Lourenco",
    "cpf": "12312399339",
    "nacionalidade": "Espanhol",
    "idade": 18
}



### LIVROS

### LISTANDO TODOS OS LIVROS

GET {{baseurl}}/livros/todos/

### LISTANDO UM LIVRO ESPECIFICO

GET {{baseurl}}/livros/2

### CRIANDO UM LIVRO NO BANCO DE DADOS
### CRIANDO UM AUTOR NO BANCO DE DADOS

POST {{baseurl}}/livros/
Content-Type: application/json

{
    "titulo": "Ronaldinho soccersss",
    "isbn": "1111211111321",
    "genero": "Futebolistico",
    "anoPublicacao": 1,
    "paginas": 100,
    "autorId": 37
}
