@baseurl = http://127.0.0.1:3000

### TESTANDO O HELLO WORLD

GET {{baseurl}}/

### AUTORES

### LISTANDO TODOS OS AUTORES

GET {{baseurl}}/autores/todos/

### LISTANDO UM AUTOR ESPECIFICO

GET {{baseurl}}/autores/3/

### CRIANDO UM AUTOR NO BANCO DE DADOS

POST {{baseurl}}/autores/
Content-Type: application/json

{
    "nome": "Gabriel Lourenco",
    "cpf": "12312320329",
    "nacionalidade": "Portugues",
    "idade": 90
}

### ATUALIZANDO UM AUTOR NO BANCO DE DADOS

PATCH {{baseurl}}/autores/3
Content-Type: application/json

{
    "nome": "Gabriel Lourenco",
    "cpf": "12312399339",
    "nacionalidade": "Espanhol",
    "idade": 18
}
### DELETANDO UM AUTOR NO BANCO DE DADOS

DELETE {{baseurl}}/autores/33/




### LIVROS

### LISTANDO TODOS OS LIVROS

GET {{baseurl}}/livros/todos/

### LISTANDO UM LIVRO ESPECIFICO

GET {{baseurl}}/livros/1

### CRIANDO UM LIVRO NO BANCO DE DADOS

POST {{baseurl}}/livros/
Content-Type: application/json

{
    "titulo": "Ronaldinho soccersss",
    "isbn": "1111211111921",
    "genero": "Futebolistico",
    "anoPublicacao": 41,
    "paginas": 100,
    "autorId": 3
}

### ATUALIZANDO UM LIVRO NO BANCO DE DADOS

PATCH {{baseurl}}/livros/1
Content-Type: application/json

{
    "titulo": "Ronaldinho ss",
    "isbn": "11111111110",
    "genero": "Futebolistico",
    "anoPublicacao": 1,
    "paginas": 100,
    "autorId": 36
}

### DELETANDO UM LIVRO NO BANCO DE DADOS

DELETE {{baseurl}}/livros/1